apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-1-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.services.ports.web1 }}
    protocol: TCP
    targetPort: {{ .Values.deployments.containerPort }}
  selector:
  {{- range $key, $val := .Values.deployments.web1.labels }}
    {{ $key }}: {{ $val }}
  {{- end }}
  type: NodePort