apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-2-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.services.ports.web2 }}
    protocol: TCP
    targetPort: {{ .Values.deployments.containerPort }}
  selector:
  {{- range $key, $val := .Values.deployments.web2.labels }}
    {{ $key }}: {{ $val }}
  {{- end }}
  type: NodePort